window_title = "Novaria"
window_width = 1280
window_height = 720
vsync = true
strict_save_mod_fingerprint = false
script_backend = "auto"
net_backend = "stub"
net_udp_local_port = 0
net_udp_remote_host = "127.0.0.1"
net_udp_remote_port = 0
